language: php
php:
  - 7
  - 7.1
  - 7.2
services:
  - mysql

matrix:
  fast_finish: true

dist: trusty
sudo: false
group: beta

env:
  - SYMFONY_ENV=test

before_install:
  - mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-interaction --prefer-dist

script:
 - composer test

cache:
  directories:
  - vendor

notifications:
  email: false
