# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    pusher:
        class: 'Pusher\Pusher'
        factory: ['AppBundle\Service\PusherFactory', createPusher]
        arguments:
            $id: '%pusher_id%'
            $key: '%pusher_key%'
            $secret: '%pusher_secret%'
            $logger: '@logger'

    fos_user_registration:
        class: 'AppBundle\EventListener\RegistrationConfirmationListener'
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
